# Generated by Django 3.2.5 on 2021-07-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quiztakers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztakers',
            options={'verbose_name': 'Quiz Taker', 'verbose_name_plural': 'Quiz Takers'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_count',
        ),
    ]
